#ifndef SHADER_H
#define SHADER_H

// 统一着色器WGSL代码
static const char* unified_vertex_shader = 
"struct VertexInput {\n"
"    @location(0) position: vec2<f32>,\n"
"    @location(1) texCoords: vec2<f32>,\n"
"    @location(2) color: vec4<f32>,\n"
"    @location(3) params: vec4<f32>,\n"      // [type, textureIndex, blendMode, reserved]
"    @location(4) geometry: vec4<f32>,\n"    // 几何参数
"    @location(5) bounds: vec4<f32>,\n"      // 包围盒
"    @location(6) zIndex: f32,\n"
"}\n"
"\n"
"struct VertexOutput {\n"
"    @builtin(position) position: vec4<f32>,\n"
"    @location(0) texCoords: vec2<f32>,\n"
"    @location(1) color: vec4<f32>,\n"
"    @location(2) params: vec4<f32>,\n"
"    @location(3) geometry: vec4<f32>,\n"
"    @location(4) bounds: vec4<f32>,\n"
"    @location(5) worldPos: vec2<f32>,\n"    // 世界坐标，用于矩形圆角计算
"}\n"
"\n"
"struct Uniforms {\n"
"    screenSize: vec2<f32>,\n"
"    time: f32,\n"
"    _padding: f32,\n"
"}\n"
"\n"
"@group(0) @binding(0) var<uniform> uniforms: Uniforms;\n"
"\n"
"@vertex\n"
"fn vs_main(input: VertexInput) -> VertexOutput {\n"
"    var output: VertexOutput;\n"
"    \n"
"    // 将屏幕坐标转换为NDC\n"
"    let ndc_x = (input.position.x / uniforms.screenSize.x) * 2.0 - 1.0;\n"
"    let ndc_y = 1.0 - (input.position.y / uniforms.screenSize.y) * 2.0;\n"
"    \n"
"    output.position = vec4<f32>(ndc_x, ndc_y, 0.0, 1.0);\n"
"    output.texCoords = input.texCoords;\n"
"    output.color = input.color;\n"
"    output.params = input.params;\n"
"    output.geometry = input.geometry;\n"
"    output.bounds = input.bounds;\n"
"    output.worldPos = input.position;\n"
"    \n"
"    return output;\n"
"}\n";

static const char* unified_fragment_shader =
"@group(1) @binding(0) var mainTexture: texture_2d<f32>;\n"
"@group(1) @binding(1) var texSampler: sampler;\n"
"\n"
"struct FragmentInput {\n"
"    @location(0) texCoords: vec2<f32>,\n"
"    @location(1) color: vec4<f32>,\n"
"    @location(2) params: vec4<f32>,\n"
"    @location(3) geometry: vec4<f32>,\n"
"    @location(4) bounds: vec4<f32>,\n"
"    @location(5) worldPos: vec2<f32>,\n"
"}\n"
"\n"
"// 圆角矩形SDF函数\n"
"fn sdf_rounded_box(p: vec2<f32>, size: vec2<f32>, radius: vec4<f32>) -> f32 {\n"
"    // 根据象限选择圆角半径\n"
"    var r: f32;\n"
"    if (p.x > 0.0) {\n"
"        if (p.y > 0.0) { r = radius.y; }  // top-right\n"
"        else { r = radius.z; }            // bottom-right\n"
"    } else {\n"
"        if (p.y > 0.0) { r = radius.x; }  // top-left\n"
"        else { r = radius.w; }            // bottom-left\n"
"    }\n"
"    \n"
"    let q = abs(p) - size + r;\n"
"    return min(max(q.x, q.y), 0.0) + length(max(q, vec2<f32>(0.0))) - r;\n"
"}\n"
"\n"
"@fragment\n"
"fn fs_main(input: FragmentInput) -> @location(0) vec4<f32> {\n"
"    let renderType = u32(input.params.x);\n"
"    let textureIndex = u32(input.params.y);\n"
"    let blendMode = u32(input.params.z);\n"
"    \n"
"    var finalColor = input.color;\n"
"    \n"
"    // 根据渲染类型处理\n"
"    switch renderType {\n"
"        case 0u: { // 矩形\n"
"            let center = input.bounds.xy + input.bounds.zw * 0.5;\n"
"            let p = input.worldPos - center;\n"
"            let halfSize = input.bounds.zw * 0.5;\n"
"            let cornerRadius = input.geometry;\n"
"            \n"
"            let d = sdf_rounded_box(p, halfSize, cornerRadius);\n"
"            let alpha = 1.0 - smoothstep(-1.0, 1.0, d);\n"
"            \n"
"            if (alpha < 0.001) {\n"
"                discard;\n"
"            }\n"
"            \n"
"            finalColor.a = finalColor.a * alpha;\n"
"        }\n"
"        case 1u: { // 文本\n"
"            let texColor = textureSample(mainTexture, texSampler, input.texCoords);\n"
"            finalColor.a = finalColor.a * texColor.r; // 使用红色通道作为alpha\n"
"            \n"
"            if (finalColor.a < 0.001) {\n"
"                discard;\n"
"            }\n"
"        }\n"
"        case 2u: { // 图片\n"
"            let texColor = textureSample(mainTexture, texSampler, input.texCoords);\n"
"            finalColor = finalColor * texColor;\n"
"            \n"
"            // 可选：应用圆角遮罩\n"
"            if (input.geometry.x > 0.0) {\n"
"                let center = input.bounds.xy + input.bounds.zw * 0.5;\n"
"                let p = input.worldPos - center;\n"
"                let halfSize = input.bounds.zw * 0.5;\n"
"                let cornerRadius = input.geometry;\n"
"                \n"
"                let d = sdf_rounded_box(p, halfSize, cornerRadius);\n"
"                let alpha = 1.0 - smoothstep(-1.0, 1.0, d);\n"
"                finalColor.a = finalColor.a * alpha;\n"
"            }\n"
"            \n"
"            if (finalColor.a < 0.001) {\n"
"                discard;\n"
"            }\n"
"        }\n"
"        case 3u: { // 边框\n"
"            let center = input.bounds.xy + input.bounds.zw * 0.5;\n"
"            let p = input.worldPos - center;\n"
"            let halfSize = input.bounds.zw * 0.5;\n"
"            let borderWidth = input.geometry.x;\n"
"            let cornerRadius = vec4<f32>(input.geometry.y, input.geometry.z, input.geometry.w, input.geometry.y);\n"
"            \n"
"            let outerD = sdf_rounded_box(p, halfSize, cornerRadius);\n"
"            let innerD = sdf_rounded_box(p, halfSize - vec2<f32>(borderWidth), cornerRadius);\n"
"            \n"
"            let outerAlpha = 1.0 - smoothstep(-1.0, 1.0, outerD);\n"
"            let innerAlpha = 1.0 - smoothstep(-1.0, 1.0, innerD);\n"
"            let borderAlpha = outerAlpha - innerAlpha;\n"
"            \n"
"            if (borderAlpha < 0.001) {\n"
"                discard;\n"
"            }\n"
"            \n"
"            finalColor.a = finalColor.a * borderAlpha;\n"
"        }\n"
"        default: {\n"
"            discard;\n"
"        }\n"
"    }\n"
"    \n"
"    return finalColor;\n"
"}\n";

#endif // SHADER_H